<?php

namespace ShopBundle\Repository;

/**
 * ProducersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducerRepository extends \Doctrine\ORM\EntityRepository
{
}
