<?php

namespace ShopBundle\Repository;

/**
 * ShoppingBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingBasketRepository extends \Doctrine\ORM\EntityRepository
{
}
