# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    vladimir:
                        password: $2y$13$/87KszIHrTIvqAxKVwP1R.nAhIc6S0DJuJsIpQeD85y.5BDlbC3i2
                        roles: 'ROLE_ADMIN'
        admin_provider:
            entity:
                class: AdminBundle\Entity\Admin
                property: username
        customer_provider:
            entity:
                class: ShopBundle\Entity\Customer
                property: email

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        AdminBundle\Entity\Admin:
            algorithm: bcrypt
        ShopBundle\Entity\Customer:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            context: main
            pattern: ^/admin
            anonymous: ~
            http-basic: ~
            provider: admin_provider
            logout:
                path:   /admin/logout
                target: /admin/login
            form_login:
                login_path: admin_login
                check_path: admin_login
                always_use_default_target_path: true
                default_target_path: admin_homepage
                csrf_token_generator: security.csrf.token_manager
#                csrf_parameter: _csrf_security_token
#                csrf_token_id: a_private_string

        main:
#            context: main
            provider: customer_provider
            pattern: ^/
            logout:
                path:   /logout
                target: /
            form_login:
                login_path: shop_login
                check_path: shop_login
                always_use_default_target_path: true
                default_target_path: shop_homepage
                csrf_token_generator: security.csrf.token_manager

            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }