ShopBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 128
            unique: true
        imageName:
            type: string
    properties:
        name:
            - NotBlank: ~
    oneToMany:
        product:
            targetEntity: ShopBundle\Entity\Product
            mappedBy: category

    lifecycleCallbacks: {  }
