ShopBundle\Entity\Categories:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\CategoriesRepository
    oneToMany:
        products:
            targetEntity: ShopBundle\Entity\Products
            mappedBy: category
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128
    lifecycleCallbacks: {  }
