ShopBundle\Entity\Categories:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\CategoriesRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 128
            unique: true
        imageName:
            type: string
    properties:
        name:
            - NotBlank: ~
    oneToMany:
        products:
            targetEntity: ShopBundle\Entity\Products
            mappedBy: categories

    lifecycleCallbacks: {  }
