ShopBundle\Entity\Customers:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\CustomersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: '128'
            unique: true
        password:
            type: string
            length: '128'
        firstName:
            type: string
            length: '128'
        secondName:
            type: string
            length: '128'
        age:
            type: smallint
        country:
            type: string
            length: '45'
        region:
            type: string
            length: '45'
        city:
            type: string
            length: '45'
        street:
            type: string
            length: '45'
        numberOfHouse:
            type: smallint
        numberOfFlat:
            type: smallint
            nullable: true
    lifecycleCallbacks: {  }
