ShopBundle\Entity\Customer:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\CustomerRepository
    id:
        id:
            type: integer
            id: true
            options:
                unsigned: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 128
            unique: true
        email:
            type: string
            length: '128'
            unique: true
        password:
            type: string
            length: '128'
        firstName:
            type: string
            length: '128'
        secondName:
            type: string
            length: '128'
        age:
            type: smallint
        country:
            type: string
            length: '45'
        region:
            type: string
            length: '45'
        city:
            type: string
            length: '45'
        street:
            type: string
            length: '45'
        numberOfHouse:
            type: smallint
        numberOfFlat:
            type: smallint
            nullable: true
        role:
            type: string
            length: 45
#    manyToMany:
#        product:
#            targetEntity: ShopBundle\Entity\Product
#            joinTable:
#                name: shopping_basket
#                joinColumnName:
#                    customer_id:
#                        referencedColumnName: id
#                        options:
#                            unsigned: true
#                        nullable: false
#                inverseJoinColumnName:
#                    product_id:
#                        referencedColumnName: id
#                        options:
#                            unsigned: true
#                        nullable: false
    oneToMany:
        shoppingBasket:
            targetEntity: ShopBundle\Entity\ShoppingBasket
            mappedBy: customer

    lifecycleCallbacks: {  }