ShopBundle\Entity\Orders:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\OrdersRepository
    id:
        id:
            type: integer
            id: true
            options:
                unsigned: true
            generator:
                strategy: AUTO
    fields:
        orderNumber:
            type: string
            length: '10'
            unique: true
    manyToOne:
        customers:
            targetEntity: ShopBundle\Entity\Customers
            joinColumns:
                customers_id:
                    referencedColumnName: id
                    options:
                        unsigned: true
                    nullable: false
    manyToMany:
        products:
            targetEntity: ShopBundle\Entity\Products
            joinTable:
                name: orders_products
                joinColumns:
                    orders_id:
                        referencedColumnName: id
                        options:
                            unsigned: true
                        nullable: false
                inverseJoinColumn:
                    products_id:
                        referencedColumnName: id
                        options:
                            unsigned: true
                        nullable: false
    lifecycleCallbacks: {  }
