ShopBundle\Entity\Orders:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\OrdersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        orderNumber:
            type: string
            length: '10'
            unique: true
    lifecycleCallbacks: {  }
