ShopBundle\Entity\Products:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\ProductsRepository
    uniqueConstraints:
        unique_name_price:
            columns: [ name, price ]
    id:
        id:
            type: integer
            options:
                unsigned: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128
        price:
            type: float
        description:
            type: text
            nullable: true
    manyToOne:
        categories:
            targetEntity: ShopBundle\Entity\Products
            jounColumns:
                categories_id:
                    referencedColumnName: id
                    options:
                        unsigned: true
                    nullable: false

        producers:
            targetEntity: ShopBundle\Entity\Producers
            joinColumns:
                producers_id:
                    referencedColumnName: id
                    options:
                        unsigned: true
                    nullable: false
    lifecycleCallbacks: {  }
