ShopBundle\Entity\Products:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\ProductsRepository
    id:
        id:
            type: integer
            options:
                unsigned: true
            id: true
        name:
            type: string
            length: 128
            id: true
        price:
            type: float
            id: true
    fields:
        description:
            type: text
            nullable: true
    manyToOne:
        categories:
            targetEntity: ShopBundle\Entity\Products
            jounColumns:
                categories_id:
                    referencedColumnName: id
        producers:
            targetEntity: ShopBundle\Entity\Producers
            joinColumns:
                producers_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
