ShopBundle\Entity\Producers:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\ProducersRepository
    id:
        id:
            type: integer
            id: true
            options:
                unsigned: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '128'
            unique: true
    lifecycleCallbacks: {  }
