ShopBundle\Entity\ShoppingBasket:
    type: entity
    table: shopping_basket
    indexes:
        fk_shopping_basket_customers_idx:
            columns:
                - customers_id
        fk_shopping_basket_products_idx:
            columns:
                - products_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
    oneToOne:
        customers:
            targetEntity: Customers
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                customers_id:
                    referencedColumnName: id
            orphanRemoval: false
        products:
            targetEntity: Products
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                products_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
