shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Products:index }

shop_show_product:
    path:     /show/category/{id}
    defaults: { _controller: ShopBundle:Products:show }
    requirements:
        id: \d+

shop_registration:
    path: /registration
    defaults: { _controller: ShopBundle:Security:registration }

shop_login:
    path: /login
    defaults: { _controller: ShopBundle:Security:login }

shop_logout:
    path: /logout

shop_add_product_to_basket:
    path: /addtobasket/{id}
    defaults: { _controller: ShopBundle:Customer:addToBasket }
    requirements:
        id: \d+

shop_customer_profile:
    path: /profile
    defaults: { _controller: ShopBundle:Customer:profile }