shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Products:index }

shop_show_product:
    path:     /show/category/{id}
    defaults: { _controller: ShopBundle:Products:show }
    requirements:
        id: \d+