ShopBundle\Entity\Categories:
    type: entity
    table: categories
    uniqueConstraints:
        name_unique:
            columns:
                - name
    id:
        id:
            type: integer
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 128
    lifecycleCallbacks: {  }
