ShopBundle\Entity\Customers:
    type: entity
    table: customers
    uniqueConstraints:
        email_unique:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        firstName:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: first_name
        secondName:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: second_name
        age:
            type: boolean
            nullable: false
        country:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        region:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        street:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        numberOfHouse:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: number_of_house
        numberOfFlat:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: number_of_flat
    lifecycleCallbacks: {  }
