ShopBundle\Entity\Orders:
    type: entity
    table: orders
    indexes:
        fk_orders_customers_idx:
            columns:
                - customers_id
    uniqueConstraints:
        order_number_unique:
            columns:
                - order_number
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
        orderNumber:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
                default: ''
            id: true
            column: order_number
    oneToOne:
        customers:
            targetEntity: Customers
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                customers_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
